### ISSUE TITLE
(Gnome) Can't select other windows in foreground mode

### ISSUE THREAD

**Issue by Titaniumtown** [weigert/splash#1]
I can't select another application when it's in foreground mode. It just moves the shape.

Cool program!

**Comment by weigert** [comment]
Can you show me what you mean with "it just moves the shape"? Do you mean the fidget spinner works?

If you launch the program by default ("splash fidget"), it spawns a window across the entire screen in foreground mode. You can change the actual size of the interaction window by using the "-p" option.

If you want to disable mouse interactions entirely, i.e. click through the splash, use the "--ni" flag.

If the behavior is still unexpected please let me know.

Also, if you could include a screenshot to show me if it works properly in gnome that would be awesome!

**Comment by Titaniumtown** [comment]
I can't select other windows, when I click or drag a window, the window doesn't move, the fidget spinner spins.

**Comment by weigert** [comment]
What you are describing is intended behavior.
Try launching with no interact and see if you can move windows: "splash fidget --ni"
Then try placing the fidget spinner in a non-maximized window! "splash fidget -p 0 0 500 500". The interaction box will have size (500, 500).

**Comment by Titaniumtown** [comment]
oh ok, I guess I didn't understand what it was supposed to do lol. thx for the tip!

**Comment by weigert** [comment]
If you can do me a favor that would be great!

If you can run the script `./test.sh` from here https://github.com/weigert/splash/tree/master/testdata on your desktop and take a screenshot (and share it) that would be awesome. Then I can add to the repo that it works on gnome! I just want to make sure that the X windows spawns borderless and the animation works.

If it doesn't work I need to iron out some bugs on gnome.

Thanks a lot!

**Comment by Titaniumtown** [comment]
oh ok. Will do
