### ISSUE TITLE
Support for X class name

### ISSUE THREAD

**Issue by b3nj5m1n** [weigert/splash#10]
As far as I can tell, the splash window doesn't have a class name, nor an instance name.

You can check that using the tool xprop. It should set a class name (Like SPLASH) by default. This would address the issue of having to do manual work in bspwm (And I imagine other tiling wm's) to get the node into floating mode. Here is a code snippet you could put into your bspwmrc to automatically set the node to floating on startup, provided it has the class & instance name "SPLASH":

`bspc rule -a SPLASH:SPLASH state=floating`

This would also make it very easy to exclude splash from shadows/blurs in compositors such as picom or the picom-tryone fork with support for kawase blur. (Currently, if you have kawase enabled and start splash, the whole screen will be blurred).

**Comment by weigert** [comment]
This is an excellent input, thank you very much. I didn't read the bspwm docs in detail enough to notice you could target classes like that. Indeed I wasn't setting the x11 WM_NAME and WM_CLASS.

I added the class and name (and indeed called them both "SPLASH"), so you can target splash with your compositor based on the name / class pair now, and set the bspc rule. Add this to your `~/.config/bspwm/bspwmrc`:

```
# Splash Float
bspc rule -a SPLASH:SPLASH state=floating
bspc rule -a SPLASH:SPLASH border=off
```

Immediately floating the window after spawning using this rule has the effect that the positioning is now also fixed. So bspwm is fully supported!

I tested this fix out on my laptop, but if you could try it out to confirm I didn't forget to mention some random setting somewhere that would be awesome! Then we can close the issue with full bspwm support.
