### ISSUE TITLE
Not working on archlinux

### ISSUE THREAD

**Issue by e3172** [weigert/splash#3]
I saw your post on r/unixporn and it looks great.
If I build it from source I get this error:

`In file included from splash.cpp:1:
splash.h:6:10: fatal error: boost/filesystem/operations.hpp: No such file or directory
    6 | #include <boost/filesystem/operations.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:7: splash] Error 1`

archlinux does not have boost_system and boost_filesystem as packages, I do have boost-libs installed though

Thank you in advance

**Comment by weigert** [comment]
It is surely possible to compile c++ with the boost libraries on arch, so this is likely fixable.

Do you know where arch package manager installs the boost libraries? Then you could look into this location and see how the libraries are actually named (should be ".so" files in there somewhere).

It is possible that either:

A: The compiler doesn't know where to find the boost libraries because the linking is not correct in the makefile. You need to change in the makefile the -L part to where ever libraries are on arch.
B: They are linked correctly but have a slightly different name on arch, and so the include directive can't find them.

As far as I know it is quite tedious to set up arch, so I'm not sure if I can setup a quick arch distro and test it out myself.

Thanks for helping test compatibility!

**Comment by b3nj5m1n** [comment]
@weigert I have the same issue, I am also on arch. It seems like arch saves the libraries in /usr/lib/ but I'm not sure how to correctly change the makefile to include them. Here are the .so filenames:
```
libboost_system.so.1.72.0 (libc6,x86-64) => /usr/lib/libboost_system.so.1.72.0
libboost_system.so.1.69.0 (libc6,x86-64) => /usr/lib/libboost_system.so.1.69.0
libboost_system.so (libc6,x86-64) => /usr/lib/libboost_system.so
libboost_filesystem.so.1.72.0 (libc6,x86-64) => /usr/lib/libboost_filesystem.so.1.72.0
libboost_filesystem.so.1.69.0 (libc6,x86-64) => /usr/lib/libboost_filesystem.so.1.69.0
libboost_filesystem.so (libc6,x86-64) => /usr/lib/libboost_filesystem.so
```
Btw, you could quickly set up a distro such as manjaro, that one is based on arch and has a very easy installer.

**Comment by weigert** [comment]
@b3nj5m1n
Thanks for the info! This is very valuable.

In the makefile, try changing the line:

`LFLAGS = -I/usr/local/include -L/usr/local/lib`

to:

`LFLAGS = -I/usr/local/include -L/usr/local/lib -L/usr/lib`

to include the libraries there. Then just compile normally with `make all`.

Let me know if that works!

If not, I might set up manjaro! Thanks for the tip.

**Comment by b3nj5m1n** [comment]
@weigert Sorry, doesn't seem to fix it.

**Comment by weigert** [comment]
Okedoke, thanks for the info. I will look into it!

Note: If anybody else reads this and manages to get it to work on arch or manjaro, please let me know how to link and include correctly! Currently it seems this is just a compilation issue with g++. So a little C++ experience would fix this quickly.

**Comment by ZeeDerp** [comment]
Currently works on Archlinux for me

**Comment by weigert** [comment]
Awesome! Thanks a lot for posting the screenshot too! Appreciate it.

I added a note in the Readme to show that it is fully compatible with arch.

Just want to note that I updated the windowing code a little bit to make it fully compatible with other DEs (XFCE, Gnome, semi-i3), so an extra flag is required in your compositor to prevent shading of the splash. It's described in the readme.

**Comment by tmpm697** [comment]
@ZeeDerp what packages need to install on arch? I installed `boost` but still have errors when running `./setup.sh`
```
make: Entering directory '/home/user/splash/splash'
In file included from splash.h:14,
                 from splash.cpp:1:
include/window.cpp:3:10: fatal error: glm/glm.hpp: No such file or directory
    3 | #include <glm/glm.hpp>
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:7: splash] Error 1

```

**Comment by tmpm697** [comment]
This is the command on arch to install all deps:

```
sudo pacman -S boost glm sdl2 sdl2_image sdl2_ttf
```
