### ISSUE TITLE
~/.config/splash/exec/fidget: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lougehrig10** [weigert/splash#6]
running ```splash fidget``` results in ```~/.config/splash/exec/fidget: cannot open shared object file: No such file or directory```

I believe I have all dependencies installed:
OpenGL, glX, GLEW, X11, xFixes, xRender, boost_system and boost_filesystem

**Comment by weigert** [comment]
Do the files exist? If they don't, then the programs did not compile. You can enter /splash/programs and do `make all` or `make fidget` specifically.

**Comment by lougehrig10** [comment]
Ah! Its because I needed to run setup.sh as sudo in order to mv splash into /usr/local/bin, but then that would move fidget into /home/root/.config/splash/exec/

**Comment by weigert** [comment]
So it worked? :)

**Comment by lougehrig10** [comment]
Yes, I just have to run sudo setup.sh and then just setup.sh. Sudo so I can install splash properly, and without so I can install fidget to my users home directory

**Comment by weigert** [comment]
Dope! Please post a screenshot of the `test.sh` script if it works :) thanks!

**Comment by SpookedMushroom** [comment]
hello I have had the same issue, when running fidget i get the error 
```
.config/splash/exec/fidget: cannot open shared object file: No such file or directory
Fatal Error: Couldn't load program fidget

``` 
I've tried running setup.sh as sudo and without sudo yet I keep getting the same error
