### ISSUE TITLE
Tested and working on bspwm

### ISSUE THREAD

**Issue by ZeeDerp** [weigert/splash#8]
fired up bspwm and it works with no issues or errors :D

**Comment by weigert** [comment]
Dope. You're the best haha. Can you post a screenshot?

If you want to go the extra mile, run the 3 test scripts in `splash/testdata/test.sh`. These test all features.

**Comment by ZeeDerp** [comment]
https://imgur.com/a/BwTU5nL The gif wasnt displaying over the terminal (i guess thats obvious because the test.sh has --bg, so the terminal isnt in the image but it exists)

**Comment by weigert** [comment]
Awesome. I just quickly set up bspwm myself to test it out. All features working!
